Many Views Many Controllers/Many Views Many Controllers/Controllers/FifthController.cs
using Microsoft.AspNetCore.Mvc;

namespace ManyViewsManyControllers.Controllers
{
    public class FifthController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Many Views Many Controllers/Many Views Many Controllers/Controllers/FourthController.cs
using Microsoft.AspNetCore.Mvc;

namespace ManyViewsManyControllers.Controllers
{
    public class FourthController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Many Views Many Controllers/Many Views Many Controllers/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace ManyViewsManyControllers.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Many Views Many Controllers/Many Views Many Controllers/Controllers/SecondController.cs
using Microsoft.AspNetCore.Mvc;

namespace ManyViewsManyControllers.Controllers
{
    public class SecondController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Many Views Many Controllers/Many Views Many Controllers/Controllers/ThirdController.cs
using Microsoft.AspNetCore.Mvc;

namespace ManyViewsManyControllers.Controllers
{
    public class ThirdController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Many Views Many Controllers/Many Views Many Controllers/Views/Fifth/Index.cshtml
<h5>The fifth controller</h5>

Many Views Many Controllers/Many Views Many Controllers/Views/Fourth/Index.cshtml
<h4>The fourth controller</h4>

Many Views Many Controllers/Many Views Many Controllers/Views/Home/Index.cshtml
<h1>The home controller</h1>

Many Views Many Controllers/Many Views Many Controllers/Views/Second/Index.cshtml
<h2>The Second controller</h2>

Many Views Many Controllers/Many Views Many Controllers/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<body>
    <ul>
        <li><a href="@Url.Action("Index", "Home")">Home</a></li>
        <li><a href="@Url.Action("Index", "Second")">Second</a></li>
        <li><a href="@Url.Action("Index", "Third")">Third</a></li>
        <li><a href="@Url.Action("Index", "Fourth")">Fourth</a></li>
        <li><a href="@Url.Action("Index", "Fifth")">Fifth</a></li>
    </ul>
    @RenderBody()
</body>
</html>

Many Views Many Controllers/Many Views Many Controllers/Views/Third/Index.cshtml
<h3>The third controller</h3>